### ISSUE TITLE
missing license file

### ISSUE THREAD

**Issue by memoryhole** [Rocketeer007/node-lcdd#7]
Hi @Rocketeer007 , what license are you releasing this code under?

**Comment by memoryhole** [comment]
@Rocketeer007 ping

**Comment by Rocketeer007** [comment]
I need to do a bit more research on licenses - there are far too many different options out there, and I don’t know enough to make the right choice yet.

Basically, I’m happy for anyone to use and develop this as they see fit, but I’d like to retain credit for it somewhere, and I don’t really want someone else profiting financially from my work (trivial as it is), so I think a flavour of GPL is probably where I’ll end up.

**Comment by Rocketeer007** [comment]
Decided that the MIT license is the way to go - I can't stop anyone profiting even with GPL, so I may as well let anyone use it as they want.
See 6ac5f93209140f54cca35d8967e60429a000bd23
